version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_DB: gdol
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass example
    ports:
      - 6379:6379

volumes:
  db_data:
    driver: local
